#ifndef __MB_ADDRESS_H
#define __MB_ADDRESS_H

//Coil address
#define COIL_SRLY1 0
#define COIL_SRLY2 1
#define COIL_SRLY3 2
#define COIL_SRLY4 3
#define COIL_DRLY1 4
#define COIL_DRLY2 5
#define COIL_DRLY3 6
#define COIL_DRLY4 7
#define COIL_SW1 8
#define COIL_SW2 9
#define COIL_SW3 10
#define COIL_SW4 11
#define COIL_SW5 12
#define COIL_SW6 13
#define COIL_ERR_NTC1 14
#define COIL_ERR_NTC2 15
#define COIL_ERR_NTC3 16
#define COIL_ERR_NTC4 17
#define COIL_ERR_SEN1 18
#define COIL_ERR_SEN2 19
#define COIL_AQI_COM 20
#define COIL_CPS_COM 21

//Inpit address
#define INPUT_STEPPER 18
#define INPUT_FAN_REASON 19
#define INPUT_CPS_STATUS_START 20
#define INPUT_CPS_STATUS_LENGTH 30

//Holding address
#define HOLDING_UPOWER 0
#define HOLDING_UMODE 1
#define HOLDING_UTEMP 2
#define HOLDING_UFAN 3

#define HOLDING_CPS_CONTROL 10
#define HOLDING_CPS_MODE 11
#define HOLDING_CPS_ROOMFAN 12
#define HOLDING_CPS_COLD_TEMP 13
#define HOLDING_CPS_COLD_INTERVAL 14
#define HOLDING_CPS_HOT_TEMP 15
#define HOLDING_CPS_HOT_INTERVAL 16
#define HOLDING_CPS_ERROR_CODE 18

#define HOLDING_NTC1 20
#define HOLDING_NTC2 21
#define HOLDING_NTC3 22
#define HOLDING_NTC4 23
#define HOLDING_S1T 24
#define HOLDING_S1H 25
#define HOLDING_S2T 26
#define HOLDING_S2H 27
#define HOLDING_EC1 28
#define HOLDING_EC2 29
#define HOLDING_EC3 30
#define HOLDING_EC4 31
#define HOLDING_STEPPER 32
#define HOLDING_AQIT 33
#define HOLDING_AQIH 34
#define HOLDING_AQIP 35
#define HOLDING_AQIC 36
#define HOLDING_AQIV 37

#endif
